language: scala
jdk: oraclejdk8
sudo: false

cache:
 directories:
  - $HOME/.m2/repository

branches:
 only:
  - master

before_script:
 - mvn versions:set -DnewVersion=1.0.$TRAVIS_BUILD_NUMBER

script:
 - mvn deploy -s settings.xml 
