language: scala
jdk: oraclejdk8
sudo: false

cache:
 directories:
  - $HOME/.m2/repository

branches:
 only:
  - master

script:
 - mvn clean versions:set deploy -s settings.xml -DnewVersion=1.0.$TRAVIS_BUILD_NUMBER
